name: Minikube CI
on: [push]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker image
        run: |
          eval $(minikube docker-env)
          docker build -t hello-app:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy.yaml
          kubectl wait --for=condition=ready pod -l app=hello-app --timeout=120s

      - name: Test the app
        run: |
          echo "Access URL: $(minikube service hello-app-service --url)"
          curl $(minikube service hello-app-service --url)
